# Implementing a Neural Network

This is inspired by <https://pub.towardsai.net/building-neural-networks-from-scratch-with-python-code-and-math-in-detail-i-536fae5d7bbf>'s "case study" with corrections.

In [1]:
%matplotlib inline

In [2]:
import time
import io

import numpy
import pandas
import matplotlib

import torch

In [3]:
input_csv = """
observation,input1,input2,output
1,0,0,0
2,0,1,1
3,1,0,1
4,1,1,1
"""

dataset = pandas.read_csv(io.StringIO(input_csv), index_col="observation")
inputs = dataset.iloc[:,:-1].to_numpy().astype('float32')
ground_truth = dataset.iloc[:,-1].to_numpy().reshape(-1, 1).astype('float32')

In [4]:
print("Inputs:\n{}".format(inputs))
print("Truth: \n{}".format(ground_truth))

Inputs:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Truth: 
[[0.]
 [1.]
 [1.]
 [1.]]


In [5]:
LEARNING_RATE = 0.05
NUM_ITERATIONS = 10000
NUM_NEURONS_HIDDEN = 3

## By Hand

In [6]:
def linear(x, weights, bias):
    return numpy.dot(x, weights) + bias

def sigmoid(x):
    return 1.0 / (1.0 + numpy.exp(-x))

def d_sigmoid(x):
    y = sigmoid(x)
    return y * (1.0 - y)

In [7]:
numpy.random.seed(seed=1)
weights_hidden = numpy.random.rand(inputs.shape[1], NUM_NEURONS_HIDDEN)
weights_output = numpy.random.rand(NUM_NEURONS_HIDDEN, 1)
# bias = numpy.random.rand(1)[0]
bias = 0.0

print("Starting hidden layer weights:\n{}\n".format(weights_hidden))
print("Starting output layer weights:\n{}".format(weights_output))

Starting hidden layer weights:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]

Starting output layer weights:
[[0.18626021]
 [0.34556073]
 [0.39676747]]


In our perceptron, 

$ y(x) = x_1 * w_1 + x_2 * w_2 + b$

### Defining the network

We use a neural network with the same number of inputs and outputs before (two inputs ($x_1$ and $x_2$), one output ($f$), but this time we add a _hidden layer_ in between with three weights for each input:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICB4MS0tIHYxIC0tLSBnMShnKVxuICAgIHgxLS0gdjEgLS0tIGcyKGcpXG4gICAgeDEtLSB2MSAtLS0gZzMoZylcbiAgICB4Mi0tIHYyIC0tLSBnMShnKVxuICAgIHgyLS0gdjIgLS0tIGcyKGcpXG4gICAgeDItLSB2MiAtLS0gZzMoZylcbiAgICBnMShnKS0tIHcxIC0tLSBmXG4gICAgZzIoZyktLSB3MiAtLS0gZlxuICAgIGczKGcpLS0gdzMgLS0tIGYiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsImZsb3djaGFydCI6eyJjdXJ2ZSI6ImJhc2lzIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICB4MS0tIHYxIC0tLSBnMShnKVxuICAgIHgxLS0gdjEgLS0tIGcyKGcpXG4gICAgeDEtLSB2MSAtLS0gZzMoZylcbiAgICB4Mi0tIHYyIC0tLSBnMShnKVxuICAgIHgyLS0gdjIgLS0tIGcyKGcpXG4gICAgeDItLSB2MiAtLS0gZzMoZylcbiAgICBnMShnKS0tIHcxIC0tLSBmXG4gICAgZzIoZyktLSB3MiAtLS0gZlxuICAgIGczKGcpLS0gdzMgLS0tIGYiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsImZsb3djaGFydCI6eyJjdXJ2ZSI6ImJhc2lzIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

These network diagrams are confusing because the definition of each node is not consistency.  So let's define our layers:

1. input values: $x$
2. hidden layer: $\hat{y} = \mathbf{x} \cdot \mathbf{v} $
  - $\hat{y}_{11} = x_{11} v_{11} + x_{12} v_{21} $
  - $\hat{y}_{21} = x_{21} v_{11} + x_{22} v_{21} $
  - ...
  - $\hat{y}_{42} = x_{41} v_{12} + x_{42} v_{22} $
  - $\hat{y}_{43} = x_{41} v_{13} + x_{42} v_{23} $
3. activation of hidden layer: $ g(\hat{y}) = \frac{1}{1+e^{-\hat{y}}} $
4. output layer: $y = \mathbf{g} \cdot \mathbf{w}$
  - $y_{11} = g_{11} w_{11} + g_{12} w_{21} + g_{13} w_{31} $
  - ...
  - $y_{41} = g_{41} w_{11} + g_{42} w_{21} + g_{43} w_{31} $
5. activation of output layer: $ f(y) = \frac{1}{1+e^{-y}} $

So our neural network with its hidden layer is really

$ f(y(g(\hat{y}(x)))) $

We choose mean-squared error as our loss function:

$ E = (f - f_0)^2 $

#### Output layer ("phase 1")

$ \frac{\partial E}{\partial w} =
\frac{\partial E}{\partial f} \cdot
\frac{\partial f}{\partial y} \cdot
\frac{\partial y}{\partial w}
$

where

- $ \frac{\partial E}{\partial f} = 2 ( f - f_0 ) $
- $ \frac{\partial f}{\partial y} = f (1 - f) $
- $ \frac{\partial y}{\partial w} = g$ (in the single-layer case, $ \frac{\partial y}{\partial w} = x $)

#### Hidden layer ("phase 2")

$ \frac{\partial E}{\partial v} = 
\frac{\partial E}{\partial g}
\frac{\partial g}{\partial \hat{y}}
\frac{\partial \hat{y}}{\partial v} $

where

- $ \frac{\partial E}{\partial g} =
           \frac{\partial E}{\partial f} \cdot
           \frac{\partial f}{\partial y} \cdot
           \frac{\partial y}{\partial g} $
    - $ \frac{\partial E}{\partial g} =
        \frac{\partial E}{\partial y} \cdot
        \frac{\partial y}{\partial g} $
    - $ \frac{\partial E}{\partial y} =
        \frac{\partial E}{\partial f} \cdot
        \frac{\partial f}{\partial y}$
- $ \frac{\partial g}{\partial \hat{y}} = g (1 - g)$
- $ \frac{\partial \hat{y}}{\partial v} = x$

In [8]:
t0 = time.time()
for i in range(NUM_ITERATIONS):
    w = weights_output
    v = weights_hidden
    yhat = linear(inputs, v, bias)
    g = sigmoid(yhat)
    y = linear(g, w, bias)
    f = sigmoid(y)
    
    error = numpy.power(f - ground_truth, 2)
    if i % (NUM_ITERATIONS / 10) == 0:
        print("error at step {:5d}: {:10.6e}".format(i, error.mean()))

    # from the tutorial
    # dE_df = f - f0
    # df_dy = f * (1 - f)
    # dy_dw = g
    # dE_dw = numpy.dot(dy_dw.T, dE_df * df_dy)
    
    # calculate out partial derivatives for each input
    dE_df = 0.5 * (f - ground_truth)
    df_dy = f * (1.0 - f)
    dy_dw = g
    dE_dy = dE_df * df_dy
    dE_dw = numpy.dot(dy_dw.T, dE_dy)
    
    # from the tutorial
#   dE_dy = dE_df * df_dy
#   dy_dg = w
#   dg_dyhat = g * (1.0 - g)
#   dE_dg = numpy.dot(dE_dy, dy_dg.T)
#   dyhat_dv = inputs
#   dE_dv = numpy.dot(dyhat_dv.T, dg_dyhat * dE_dg)
    
    # calculate partial derivatives with respect to hidden layer weights
    dy_dg = w
    dE_dg = numpy.dot(dE_dy, dy_dg.T)
    dg_dyhat = g * (1.0 - g)
    dyhat_dv = inputs
    dE_dyhat = dE_dg * dg_dyhat
    dE_dv = numpy.dot(dyhat_dv.T, dE_dyhat)
    
    # update weights and biases - the error is the sum of error over each input
    if NUM_ITERATIONS == 1:
        print("dE_dv:\n{}".format(dE_dv))
        print("dE_dw:\n{}".format(dE_dw))
    weights_hidden -= LEARNING_RATE * dE_dv
    weights_output -= LEARNING_RATE * dE_dw
#   bias -= LEARNING_RATE * dE_dy.sum()

print("Final weights:")
print("       hidden: {}".format(weights_hidden.flatten()))
print("       output: {}".format(weights_output.flatten()))
print("Final bias:    {}".format(bias))
print("{:d} iterations took {:.1f} seconds".format(NUM_ITERATIONS, time.time() - t0))

error at step     0: 1.960156e-01
error at step  1000: 1.651662e-01
error at step  2000: 1.593565e-01
error at step  3000: 1.550351e-01
error at step  4000: 1.511067e-01
error at step  5000: 1.465351e-01
error at step  6000: 1.392272e-01
error at step  7000: 1.234844e-01
error at step  8000: 9.350530e-02
error at step  9000: 6.205274e-02
Final weights:
       hidden: [ 1.66707072  2.43454525 -1.50667653  1.66659174  2.29166158 -1.50681196]
       output: [ 0.70570663  2.04736287 -4.12867523]
Final bias:    0.0
10000 iterations took 2.1 seconds


In [9]:
# traverse the hidden layer
predicted_output = linear(inputs, weights_hidden, bias)
predicted_output = sigmoid(predicted_output)
# traverse the output layer
predicted_output = linear(predicted_output, weights_output, bias)
predicted_output = sigmoid(predicted_output)

# convert output to dataframe
predicted_output = pandas.DataFrame(
    predicted_output,
    columns=["prediction"],
    index=dataset.index)

output = pandas.concat(
    (dataset, predicted_output),
    axis=1)
output['error'] = output['output'] - output['prediction']
output

input1  input2  output  prediction     error
observation                                              
1                 0       0       0    0.334522 -0.334522
2                 0       1       1    0.846053  0.153947
3                 1       0       1    0.849022  0.150978
4                 1       1       1    0.925358  0.074642

## PyTorch

In [10]:
# torch.manual_seed(0)

model = torch.nn.Sequential(
    torch.nn.Linear(inputs.shape[1], NUM_NEURONS_HIDDEN, bias=False),
    torch.nn.Sigmoid(),
    torch.nn.Linear(NUM_NEURONS_HIDDEN, 1, bias=False),
    torch.nn.Sigmoid()
)

In [11]:
numpy.random.seed(seed=1) # use same initial seed as before

with torch.no_grad():
    # torch.rand() is faster, but we use numpy to re-use the same random starting weights/biases
    model[0].weight = torch.nn.Parameter(torch.from_numpy(numpy.random.rand(inputs.shape[1], NUM_NEURONS_HIDDEN).T))
    # model[0].bias = torch.nn.Parameter(torch.from_numpy(numpy.random.rand(1, 1)))
    model[2].weight = torch.nn.Parameter(torch.from_numpy(numpy.random.rand(NUM_NEURONS_HIDDEN, 1).T))
print("Starting hidden layer weights:\n{}\n".format(model[0].weight))
print("Starting output layer weights:\n{}".format(model[2].weight))
# print("Starting bias: {}".format(model[0].bias.flatten()))

Starting hidden layer weights:
Parameter containing:
tensor([[4.1702e-01, 3.0233e-01],
        [7.2032e-01, 1.4676e-01],
        [1.1437e-04, 9.2339e-02]], dtype=torch.float64, requires_grad=True)

Starting output layer weights:
Parameter containing:
tensor([[0.1863, 0.3456, 0.3968]], dtype=torch.float64, requires_grad=True)


In [12]:
inputs_tensor = torch.from_numpy(inputs.astype(numpy.float64))
truth_tensor = torch.from_numpy(ground_truth.reshape(-1, 1).astype(numpy.float64))

loss = torch.nn.MSELoss(reduction='mean')

optimizer = torch.optim.SGD(model.parameters(), lr=LEARNING_RATE)

model.train()
t0 = time.time()
for i in range(NUM_ITERATIONS):
    f = model(inputs_tensor)

    error = loss(f, truth_tensor)
    if i % (NUM_ITERATIONS / 10) == 0:
        print("error at step {:5d}: {:10.6e}".format(i, error.mean()))

    optimizer.zero_grad()
    
    error.backward()

    if NUM_ITERATIONS == 1:
        print("dE_dv:\n{}".format(model[0].weight.grad.detach().numpy()))
        print("dE_dw:\n{}".format(model[2].weight.grad.detach().numpy()))
    
    optimizer.step()


print("Final weights:")
print("       hidden: {}".format(next(model[0].parameters()).detach().numpy().flatten()))
print("       output: {}".format(next(model[2].parameters()).detach().numpy().flatten()))

print("{:d} iterations took {:.1f} seconds".format(NUM_ITERATIONS, time.time() - t0))

error at step     0: 1.960156e-01
error at step  1000: 1.651662e-01
error at step  2000: 1.593565e-01
error at step  3000: 1.550351e-01
error at step  4000: 1.511067e-01
error at step  5000: 1.465351e-01
error at step  6000: 1.392272e-01
error at step  7000: 1.234844e-01
error at step  8000: 9.350530e-02
error at step  9000: 6.205274e-02
Final weights:
       hidden: [ 1.66707072  1.66659174  2.43454525  2.29166158 -1.50667653 -1.50681196]
       output: [ 0.70570663  2.04736287 -4.12867523]
10000 iterations took 10.3 seconds


In [13]:
model.eval()

predicted_output = model(inputs_tensor).detach().numpy()
predicted_output = pandas.DataFrame(
    predicted_output,
    columns=["prediction"],
    index=dataset.index)

output = pandas.concat(
    (dataset, predicted_output),
    axis=1)
output['error'] = output['output'] - output['prediction']
output

input1  input2  output  prediction     error
observation                                              
1                 0       0       0    0.334522 -0.334522
2                 0       1       1    0.846053  0.153947
3                 1       0       1    0.849022  0.150978
4                 1       1       1    0.925358  0.074642